### ISSUE TITLE
Provide vector-returning alternatives for normalize/relativize/resolve

### ISSUE THREAD

**Issue by cemerick** [davidsantiago/pathetic#1]
Right now, these fns all take and return strings.  It'd be great if alternatives (e.g. `normalize*`, `relativize*`, `resolve*`) accepted and returned vector representations of the paths involved.  Obviously, the current API would delegate to those alternatives (almost as simple as e.g. `(comp render-path normalize* parse-path)`).

**Comment by davidsantiago** [comment]
This is done in version 0.3.1, thanks. 

   David
